# Context: ./.config/nvim/other-apps/ipynb/
FROM python:3.13-alpine3.22 as builder

# podman pull python:3.13-alpine3.22
# podman run --rm -it --entrypoint=/bin/sh python:3.13-alpine3.22


WORKDIR /tests
COPY ./.config/nvim/other-apps/ipynb/requirements.txt .

ENV NVIM_USER="nvim"

RUN <<EOF

TARGET_SCRIPT_PATH="/scripts/jupynvim.sh"

build_routine() {
    if ! ( MODE="build" . "${TARGET_SCRIPT_PATH}" ); then
    echo "|> [ERROR]: could not run the [build] function of the [TARGET_SCRIPT_PATH]. Exiting now..."
    return 1

    fi
    echo "|> [PASS]: successfully ran the [build] function of the [TARGET_SCRIPT_PATH]. Proceeding..."
}
build_routine


EOF


#NVIM_USER 1000
#WORKDIR /$NVIM_USER/rice/

COPY . .
RUN ls -allhtr
RUN <<EOF

#set_packer() {
#}

set_lazy()

set_coq()

nvim_tests() {
for dir in /test/*; do
    if [ -d $dir ]; then
    nvim --headless -u NONE -c "luafile $dir/hullo.lua" -c ":qa" >> /test/test_result_"$(basename "$dir")"_.txt 2>&1
    cd - || return
    elif [ -f "$dir" ]; then
        echo "A file $dir was found. Skipping..."
    fi
done
}

su "${NVIM_USER}" && nvim_tests
EOF


ENTRYPOINT ["MODE='entrypoint' . ./scripts/jupynvim.sh"]

#ENTRYPOINT [ "nvim", "--headless", "-c" , "'so'", "-c", "'PackerSync'", "'${HOME}/.config/nvim/lua/user/packer.lua'" ]


# =========
# relay step
#
FROM alpine:3.20 as relay

COPY --from=builder /test/test_result_*_.txt .

ENTRYPOINT ["/bin/sh", "-c"]

CMD ["cat /tests/test_result_*_.txt"]

