-- ### local telescope = require('telescope')
-- ### telescope.setup {
-- ###     pickers = {
-- ###         find_files = {
-- ###             hidden = true,
-- ###
-- ###             find_command = {
-- ###               "rg",
-- ###               "--files",
-- ###               "--hidden",
-- ###               "-g",
-- ###               "!.git",
-- ###               "--glob=!**/.git/*",
-- ###               "--glob=!**/.idea/*",
-- ###               "--glob=!**/.vscode/*",
-- ###               "--glob=!**/build/*",
-- ###               "--glob=!**/dist/*",
-- ###               "--glob=!**/yarn.lock",
-- ###               "--glob=!**/package-lock.json",
-- ###             }}
-- ###     },
-- ###
-- ###     vimgrep_arguments = {
-- ###         "rg",
-- ###         "--follow",        -- Follow symbolic links
-- ###         "--hidden",        -- Search for hidden files
-- ###         "--no-heading",    -- Don't group matches by each file
-- ###         "--with-filename", -- Print the file path with the matched lines
-- ###         "--line-number",   -- Show line numbers
-- ###         "--column",        -- Show column numbers
-- ###         "--smart-case",    -- Smart case search
-- ###         "--hidden-flags",
-- ###         "--no-ignore-vcs",
-- ###
-- ###         -- Exclude some patterns from search
-- ###         "--glob=!**/.git/*",
-- ###         "--glob=!**/.idea/*",
-- ###         "--glob=!**/.vscode/*",
-- ###         "--glob=!**/build/*",
-- ###         "--glob=!**/dist/*",
-- ###         "--glob=!**/yarn.lock",
-- ###         "--glob=!**/package-lock.json",
-- ###         "--glob=!**/*org.eclipse.*", --eclipse/maven/java specific.
-- ###         "--glob=!**/*venv_nvim*",
-- ###     }
-- ### }
